name: FastJack

valves:
  IGNITER: DIO6

sensors:
  - name: P20
    port: AIN3
    range: 10
    multiplier: 100

  - name: P30
    port: AIN2
    range: 10
    multiplier: 100

  - name: LC
    port: AIN0
    negative_channel: AIN1
    multiplier: -200

