valves:
  "V11_NO": "DIO0"
  "V30": "DIO1"
  "V12_NO": "DIO2"
  "V31": "DIO3"
  "V20": "DIO4"
  "V32": "DIO5"
  "V21": "DIO6"
  "V33": "DIO7"
  "V35_NO": "DIO8"
  "V36": "DIO9"
  "V34": "DIO10"
  "V38_NO": "DIO11"
  "V37": "DIO12"
  "V23_NO": "DIO13"
  "V10": "DIO14"
  "V22": "DIO15"

sensors:
  - name: "P31"
    port: "AIN0"
    settings:
      "RANGE": 10.0
  - name: "P21"
    port: "AIN2"
    settings:
      "RANGE": 10.0
  - name: "P10"
    port: "AIN4"
    settings:
      "RANGE": 10.0
  - name: "P22"
    port: "AIN11"
    settings:
      "RANGE": 10.0
  - name: "P32"
    port: "AIN3"
    settings:
      "RANGE": 10.0
  - name: "T1"
    port: "AIN7"
    settings:
      "THERMOCOUPLE_TYPE": K
  - name: "T2"
    port: "AIN9"
    settings:
      "THERMOCOUPLE_TYPE": K
  - name: "PINJ"
    port: "AIN4"
    settings:
      "RANGE": 10.0
  - name: "LC"
    port: "AIN0"
    settings:
      "NEGATIVE_PORT": AIN1
  - name: "INJ1"
    port: "AIN10"
    settings:
      "RANGE": 0.1
      "NEGATIVE_PORT": AIN11
  - name: "INJ2"
    port: "AIN8"
    settings:
      "RANGE": 0.1
      "NEGATIVE_PORT": AIN9
  - name: "IGN"
    port: "AIN6"
    settings:
      "RANGE": 0.1
      "NEGATIVE_PORT": AIN7
  - name: "P20"
    port: "AIN3"
    settings:
      "RANGE": 10
  - name: "P30"
    port: "AIN2"
    settings:
      "RANGE": 10