sequences:
  - name: "igniter"
    steps:
      - action: open
        item: "DIO6"
        duration: 5
      - action: close
        item: "DIO6"
        duration: 0
  - name: "stop"
    steps:
      - action: close
        item: "V10"
        duration: 0
      - action: close
        item: "V21"
        duration: 0
      - action: close
        item: "V20"
        duration: 0
      - action: close
        item: "V30"
        duration: 0
      - action: close
        item: "V31"
        duration: 0
      - action: close
        item: "V32"
        duration: 0
      - action: close
        item: "V34"
        duration: 0
      - action: close
        item: "V36"
        duration: 0
      - action: close
        item: "V37"
        duration: 0
      - action: close
        item: "V11_NO"
        duration: 0
      - action: close
        item: "V12_NO"
        duration: 0
      - action: close
        item: "V22"
        duration: 0
      - action: close
        item: "V23_NO"
        duration: 0
      - action: close
        item: "V33"
        duration: 0
      - action: close
        item: "V35_NO"
        duration: 0
      - action: close
        item: "V38_NO"
        duration: 0
  - name: "oxidizer"
    steps:
      - action: open
        item: "V34"
        duration: 10
      - action: close
        item: "V34"
        duration: 0
      - action: open
        item: "V30"
        duration: 3
      - action: close
        item: "V30"
        duration: 0
      - action: close
        item: "V31"
        duration: 0
      - action: open
        item: "V33"
        duration: 7
      - action: close
        item: "V33"
        duration: 0
  - name: "alternate oxidizer"
    steps:
      - action: open
        item: "V34"
        duration: 10
      - action: close
        item: "V34"
        duration: 0
      - action: open
        item: "V30"
        duration: 7
      - action: close
        item: "V30"
        duration: 0
      - action: close
        item: "V31"
        duration: 0
      - action: open
        item: "V33"
        duration: 3
      - action: close
        item: "V33"
        duration: 0
  - name: "ignition"
    steps:
      - action: open
        item: "V34"
        duration: 10
      - action: open
        item: "DIO6"
        duration: 0
      - action: check
        item: "IGN"
        value: 365
      - action: close
        item: "V34"
        duration: 0
      - action: open
        item: "V20"
        duration: 0
      - action: open
        item: "V30"
        duration: 4.5
      - action: close
        item: "V30"
        duration: 0
      - action: open
        item: "V33"
        duration: 2.5
      - action: close
        item: "V20"
        duration: 0
      - action: open
        item: "V22"
        duration: 3
      - action: close
        item: "V33"
        duration: 0
      - action: close
        item: "V22"
        duration: 0
      - action: close
        item: "V31"
        duration: 0
      - action: close
        item: "V10"
        duration: 0