steps:
  - action: OPEN
    valve: V34

  - action: SLEEP
    duration: 10

  - action: CLOSE
    valve: V34

  - action: OPEN
    valve: V30
  
  - action: SLEEP
    duration: 7

  - action: CLOSE
    valve: V30

  - action: CLOSE
    valve: V31

  - action: OPEN
    valve: V33

  - action: SLEEP
    duration: 3

  - action: CLOSE
    valve: V33
