steps:
  - action: SLEEP
    duration: 10

  - action: OPEN
    valve: V30

  - action: SLEEP
    duration: 0.15

  - action: OPEN
    valve: V20

  - action: SLEEP
    duration: 4.5

  - action: CLOSE
    valve: V30

  - action: OPEN
    valve: V33

  - action: SLEEP
    duration: 2.5

  - action: CLOSE
    valve: V20

  - action: OPEN
    valve: V22

  - action: SLEEP
    duration: 3

  - action: CLOSE
    valve: V33

  - action: CLOSE
    valve: V22

  - action: CLOSE
    valve: V31

  - action: CLOSE
    valve: V10
