steps:
  - action: OPEN
    item: V34

  - action: SLEEP
    duration: 10

  - action: OPEN
    item: DIO6

  - action: CHECK
    item: IGN
    value: 365

  - action: CLOSE
    item: V34

  - action: OPEN
    item: V20

  - action: OPEN
    item: V30

  - action: SLEEP
    duration: 4.5

  - action: CLOSE
    item: V30

  - action: OPEN
    item: V33

  - action: SLEEP
    duration: 2.5

  - action: CLOSE
    item: V20

  - action: OPEN
    item: V22

  - action: SLEEP
    duration: 3

  - action: CLOSE
    item: V33

  - action: CLOSE
    item: V22

  - action: CLOSE
    item: V31

  - action: CLOSE
    item: V10
