steps:
  - action: OPEN
    item: V34

  - action: SLEEP
    duration: 10

  - action: CLOSE
    item: V34

  - action: OPEN
    item: V30

  - action: SLEEP
    duration: 3

  - action: CLOSE
    item: V30

  - action: CLOSE
    item: V31

  - action: OPEN
    item: V33

  - action: SLEEP
    duration: 7

  - action: CLOSE
    item: V33
