sequences:
  - name: ignition
    steps:
      - action: OPEN
        valve: V34
        duration: 10
      - action: OPEN
        valve: DIO6
        duration: 0
      - action: check
        valve: IGN
        value: 365
      - action: CLOSE
        valve: V34
        duration: 0
      - action: OPEN
        valve: V20
        duration: 0
      - action: OPEN
        valve: V30
        duration: 4.5
      - action: CLOSE
        valve: V30
        duration: 0
      - action: OPEN
        valve: V33
        duration: 2.5
      - action: CLOSE
        valve: V20
        duration: 0
      - action: OPEN
        valve: V22
        duration: 3
      - action: CLOSE
        valve: V33
        duration: 0
      - action: CLOSE
        valve: V22
        duration: 0
      - action: CLOSE
        valve: V31
        duration: 0
      - action: CLOSE
        valve: V10
        duration: 0